package io.ciphertun.ghi.feature.discover

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.dp
import io.ciphertun.ghi.core.designsystem.GhiInk900
import io.ciphertun.ghi.core.ui.components.*

private val methods=listOf("GET","HEAD","POST","PUT","PATCH","DELETE","OPTIONS","CONNECT","TRACE")
private val variants=listOf("Standard","Absolute-form","Keep-Alive","WebSocket Upgrade")

@Composable fun PayloadGeneratorScreen(){
    var host by remember{mutableStateOf("")};var scheme by remember{mutableStateOf("https")};var path by remember{mutableStateOf("/")};var userAgent by remember{mutableStateOf("GlobalHostIntelligence/3.0")};var generated by remember{mutableStateOf<List<Pair<String,String>>>(emptyList())};val clipboard=LocalClipboardManager.current
    GhiScreenScaffold("Payload Generator"){modifier->LazyColumn(modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp),contentPadding=PaddingValues(bottom=24.dp)){
        item{GhiHero("HTTP request builder","Generate real raw HTTP request templates from the same fields used by the Response Checker. No fake payloads.")}
        item{GhiCard{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(host,{host=it},label={Text("Domain / host")},placeholder={Text("example.com")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(path,{path=it},label={Text("Path")},singleLine=true,modifier=Modifier.fillMaxWidth());OutlinedTextField(userAgent,{userAgent=it},label={Text("User-Agent")},singleLine=true,modifier=Modifier.fillMaxWidth());Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){SchemeButton("HTTP",scheme=="http"){scheme="http"};SchemeButton("HTTPS",scheme=="https"){scheme="https"}};Button(enabled=host.isNotBlank(),onClick={generated=buildPayloads(host.trim(),scheme,path,userAgent)},modifier=Modifier.fillMaxWidth().height(50.dp)){Icon(Icons.Filled.Refresh,null);Spacer(Modifier.width(8.dp));Text("GENERATE ALL")}}}}
        if(generated.isNotEmpty()){item{Row{Text("${generated.size} requests",style=MaterialTheme.typography.titleMedium,modifier=Modifier.weight(1f));TextButton(onClick={clipboard.setText(AnnotatedString(generated.joinToString("\n\n"){it.second}))}){Icon(Icons.Filled.ContentCopy,null);Spacer(Modifier.width(5.dp));Text("COPY ALL")}}}}
        items(generated,key={it.first}){(name,payload)->GhiCard{Column(Modifier.fillMaxWidth().padding(12.dp)){Row{Text(name,style=MaterialTheme.typography.titleSmall,modifier=Modifier.weight(1f));IconButton(onClick={clipboard.setText(AnnotatedString(payload))}){Icon(Icons.Filled.ContentCopy,"Copy")}};Surface(color=GhiInk900.copy(alpha=.8f),shape=MaterialTheme.shapes.small){Text(payload,style=MaterialTheme.typography.bodySmall,modifier=Modifier.fillMaxWidth().padding(10.dp))}}}}
    }}
}
private fun buildPayloads(host:String,scheme:String,path:String,ua:String):List<Pair<String,String>>{val clean=host.removePrefix("https://").removePrefix("http://").trimEnd('/');val p=if(path.startsWith('/'))path else "/$path";val out=mutableListOf<Pair<String,String>>();methods.forEach{method->val body=if(method in listOf("POST","PUT","PATCH")){"{}"}else"";val lines=mutableListOf("$method $p HTTP/1.1","Host: $clean","User-Agent: $ua","Accept: */*");if(body.isNotEmpty()){lines+="Content-Type: application/json";lines+="Content-Length: ${body.toByteArray().size}"};out+="$scheme • $method • Standard" to lines.plus("").plus(body).joinToString("\r\n")};out+="$scheme • GET • Absolute-form" to "GET $scheme://$clean$p HTTP/1.1\r\nHost: $clean\r\nUser-Agent: $ua\r\nAccept: */*\r\n\r\n";out+="$scheme • GET • Keep-Alive" to "GET $p HTTP/1.1\r\nHost: $clean\r\nConnection: keep-alive\r\nUser-Agent: $ua\r\nAccept: */*\r\n\r\n";out+="$scheme • GET • WebSocket Upgrade" to "GET $p HTTP/1.1\r\nHost: $clean\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nUser-Agent: $ua\r\n\r\n";return out}
@Composable private fun SchemeButton(label:String,selected:Boolean,onClick:()->Unit){if(selected)Button(onClick=onClick){Text(label)}else OutlinedButton(onClick=onClick){Text(label)}}
