package io.ciphertun.ghi.feature.discover

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.dp
import io.ciphertun.ghi.core.designsystem.GhiInk800
import io.ciphertun.ghi.core.ui.components.*

private val methods = listOf("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "CONNECT", "TRACE")
private val variants = listOf("Standard", "Absolute-form", "Keep-Alive", "WebSocket Upgrade")

@Composable
fun PayloadGeneratorScreen() {
    var host by remember { mutableStateOf("") }
    var scheme by remember { mutableStateOf("https") }
    var generated by remember { mutableStateOf<List<Pair<String, String>>>(emptyList()) }
    val clipboard = LocalClipboardManager.current

    GhiScreenScaffold("Payload Generator") { modifier ->
        LazyColumn(modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp), contentPadding = PaddingValues(bottom = 24.dp)) {
            item { GhiHero("Automatic payload generator", "Enter a domain and choose HTTP or HTTPS. GHI generates the standard request variants automatically.") }
            item {
                OutlinedTextField(host, { host = it }, label = { Text("Domain") }, placeholder = { Text("example.com") }, modifier = Modifier.fillMaxWidth(), singleLine = true)
            }
            item {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    SchemeButton("HTTP", scheme == "http") { scheme = "http" }
                    SchemeButton("HTTPS", scheme == "https") { scheme = "https" }
                }
            }
            item {
                Button(enabled = host.isNotBlank(), onClick = { generated = buildPayloads(host.trim(), scheme) }, modifier = Modifier.fillMaxWidth().height(52.dp)) { Icon(Icons.Filled.Refresh, null); Spacer(Modifier.width(8.dp)); Text("GENERATE ALL") }
            }
            if (generated.isNotEmpty()) {
                item {
                    Row { Text("${generated.size} payloads", style = MaterialTheme.typography.titleMedium, modifier = Modifier.weight(1f)); TextButton(onClick = { clipboard.setText(AnnotatedString(generated.joinToString("\n\n") { it.second })) }) { Icon(Icons.Filled.ContentCopy, null); Spacer(Modifier.width(5.dp)); Text("COPY ALL") } }
                }
                items(generated, key = { it.first }) { (name, payload) ->
                    GhiCard {
                        Column(Modifier.fillMaxWidth().padding(12.dp)) {
                            Row { Text(name, style = MaterialTheme.typography.titleSmall, modifier = Modifier.weight(1f)); IconButton(onClick = { clipboard.setText(AnnotatedString(payload)) }) { Icon(Icons.Filled.ContentCopy, "Copy $name") } }
                            Surface(color = GhiInk800, shape = MaterialTheme.shapes.small) { Text(payload, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(10.dp)) }
                        }
                    }
                }
            }
        }
    }
}

private fun buildPayloads(host: String, scheme: String): List<Pair<String, String>> {
    val clean = host.removePrefix("https://").removePrefix("http://").trimEnd('/')
    val out = mutableListOf<Pair<String, String>>()
    methods.forEach { method ->
        val body = if (method in listOf("POST", "PUT", "PATCH")) "{}" else ""
        val lines = mutableListOf("$method / HTTP/1.1", "Host: $clean", "User-Agent: GlobalHostIntelligence/2.3", "Accept: */*")
        if (body.isNotEmpty()) { lines += "Content-Type: application/json"; lines += "Content-Length: ${body.toByteArray().size}" }
        out += "$scheme • $method • Standard" to lines.plus("").plus(body).joinToString("\r\n")
    }
    out += "$scheme • GET • Absolute-form" to "GET $scheme://$clean/ HTTP/1.1\r\nHost: $clean\r\nUser-Agent: GlobalHostIntelligence/2.3\r\nAccept: */*\r\n\r\n"
    out += "$scheme • GET • Keep-Alive" to "GET / HTTP/1.1\r\nHost: $clean\r\nConnection: keep-alive\r\nUser-Agent: GlobalHostIntelligence/2.3\r\nAccept: */*\r\n\r\n"
    out += "$scheme • GET • WebSocket Upgrade" to "GET / HTTP/1.1\r\nHost: $clean\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\n\r\n"
    return out
}

@Composable private fun SchemeButton(label: String, selected: Boolean, onClick: () -> Unit) { if (selected) Button(onClick = onClick) { Text(label) } else OutlinedButton(onClick = onClick) { Text(label) } }
