package io.ciphertun.ghi.feature.discover

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Code
import androidx.compose.material.icons.filled.Http
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import io.ciphertun.ghi.core.designsystem.GhiInk900
import io.ciphertun.ghi.core.designsystem.GhiSignalAmber
import io.ciphertun.ghi.core.designsystem.GhiSignalGreen
import io.ciphertun.ghi.core.designsystem.GhiSlate300
import io.ciphertun.ghi.core.ui.components.*

private const val CURRENT_CHROME_ANDROID_UA =
    "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/153.0.0.0 Mobile Safari/537.36"

private val methods = listOf("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")

private data class PayloadVariant(
    val name: String,
    val raw: String,
    val curl: String,
    val fetch: String
)

private data class PayloadValidation(
    val ok: Boolean,
    val message: String,
    val bytes: Int,
    val headerCount: Int
)

@Composable
fun PayloadGeneratorScreen() {
    var host by remember { mutableStateOf("") }
    var scheme by remember { mutableStateOf("https") }
    var path by remember { mutableStateOf("/") }
    var method by remember { mutableStateOf("GET") }
    var userAgent by remember { mutableStateOf(CURRENT_CHROME_ANDROID_UA) }
    var headers by remember { mutableStateOf("") }
    var contentType by remember { mutableStateOf("application/json") }
    var body by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<List<PayloadVariant>>(emptyList()) }
    var validation by remember { mutableStateOf<PayloadValidation?>(null) }
    val clipboard = LocalClipboardManager.current

    GhiScreenScaffold("Payload Generator") { modifier ->
        LazyColumn(
            modifier.fillMaxSize().padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
            contentPadding = PaddingValues(bottom = 24.dp)
        ) {
            item {
                GhiHero(
                    "REAL HTTP REQUEST LAB",
                    "Construct protocol-valid HTTP/1.1 requests, validate them, and export runnable client snippets."
                )
            }

            item {
                GhiCard {
                    Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                        OutlinedTextField(
                            host,
                            { host = it; validation = null },
                            label = { Text("Domain / host") },
                            placeholder = { Text("example.com") },
                            singleLine = true,
                            modifier = Modifier.fillMaxWidth()
                        )
                        OutlinedTextField(
                            path,
                            { path = it; validation = null },
                            label = { Text("Path + query") },
                            placeholder = { Text("/api/status?full=1") },
                            singleLine = true,
                            modifier = Modifier.fillMaxWidth()
                        )

                        Text("Scheme", style = MaterialTheme.typography.labelLarge)
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            SchemeButton("HTTP", scheme == "http") { scheme = "http" }
                            SchemeButton("HTTPS", scheme == "https") { scheme = "https" }
                        }

                        Text("Method", style = MaterialTheme.typography.labelLarge)
                        Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                            methods.chunked(4).forEach { row ->
                                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                                    row.forEach { item ->
                                        if (method == item) Button(onClick = { method = item }) { Text(item) }
                                        else OutlinedButton(onClick = { method = item }) { Text(item) }
                                    }
                                }
                            }
                        }

                        OutlinedTextField(
                            userAgent,
                            { userAgent = it },
                            label = { Text("User-Agent") },
                            supportingText = { Text("Chrome Android reduced UA • Chrome 153 stable") },
                            modifier = Modifier.fillMaxWidth()
                        )

                        OutlinedTextField(
                            headers,
                            { headers = it; validation = null },
                            label = { Text("Extra headers") },
                            placeholder = { Text("Accept: application/json\nCache-Control: no-cache") },
                            minLines = 3,
                            modifier = Modifier.fillMaxWidth()
                        )

                        if (method in setOf("POST", "PUT", "PATCH")) {
                            OutlinedTextField(
                                contentType,
                                { contentType = it },
                                label = { Text("Content-Type") },
                                singleLine = true,
                                modifier = Modifier.fillMaxWidth()
                            )
                            OutlinedTextField(
                                body,
                                { body = it; validation = null },
                                label = { Text("Request body") },
                                placeholder = { Text("{\"key\":\"value\"}") },
                                minLines = 4,
                                modifier = Modifier.fillMaxWidth()
                            )
                        }

                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                            Button(
                                enabled = host.isNotBlank(),
                                onClick = {
                                    val result = buildPayloads(host, scheme, method, path, userAgent, headers, contentType, body)
                                    generated = result
                                    validation = validateRequest(result.firstOrNull()?.raw.orEmpty())
                                },
                                modifier = Modifier.weight(1f).height(50.dp)
                            ) {
                                Icon(Icons.Filled.Code, null)
                                Spacer(Modifier.width(7.dp))
                                Text("BUILD")
                            }
                            OutlinedButton(
                                enabled = generated.isNotEmpty(),
                                onClick = { validation = validateRequest(generated.first().raw) },
                                modifier = Modifier.weight(1f).height(50.dp)
                            ) {
                                Icon(Icons.Filled.CheckCircle, null)
                                Spacer(Modifier.width(7.dp))
                                Text("VALIDATE")
                            }
                        }
                    }
                }
            }

            validation?.let { v ->
                item {
                    GhiCard {
                        Row(Modifier.padding(14.dp), verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                if (v.ok) Icons.Filled.CheckCircle else Icons.Filled.Warning,
                                null,
                                tint = if (v.ok) GhiSignalGreen else GhiSignalAmber
                            )
                            Spacer(Modifier.width(10.dp))
                            Column(Modifier.weight(1f)) {
                                Text(if (v.ok) "REQUEST VALID" else "REQUEST NEEDS ATTENTION", fontWeight = FontWeight.Bold)
                                Text(v.message, color = GhiSlate300, style = MaterialTheme.typography.bodySmall)
                                Text("${v.bytes} bytes • ${v.headerCount} headers", color = GhiSlate300, style = MaterialTheme.typography.labelSmall)
                            }
                        }
                    }
                }
            }

            if (generated.isNotEmpty()) {
                item {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Column(Modifier.weight(1f)) {
                            Text("${generated.size} request variants", style = MaterialTheme.typography.titleMedium)
                            Text("Raw HTTP + cURL + Fetch", color = GhiSlate300, style = MaterialTheme.typography.labelSmall)
                        }
                        TextButton(onClick = { clipboard.setText(AnnotatedString(generated.joinToString("\n\n") { it.raw })) }) {
                            Icon(Icons.Filled.ContentCopy, null)
                            Spacer(Modifier.width(5.dp))
                            Text("COPY ALL")
                        }
                    }
                }
            }

            items(generated, key = { it.name }) { item ->
                PayloadVariantCard(item, clipboard)
            }
        }
    }
}

@Composable
private fun PayloadVariantCard(item: PayloadVariant, clipboard: androidx.compose.ui.platform.ClipboardManager) {
    var tab by remember(item.name) { mutableIntStateOf(0) }
    val content = when (tab) {
        1 -> item.curl
        2 -> item.fetch
        else -> item.raw
    }
    GhiCard {
        Column(Modifier.fillMaxWidth().padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(Icons.Filled.Http, null, tint = MaterialTheme.colorScheme.primary)
                Spacer(Modifier.width(8.dp))
                Text(item.name, style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, modifier = Modifier.weight(1f))
                IconButton(onClick = { clipboard.setText(AnnotatedString(content)) }) { Icon(Icons.Filled.ContentCopy, "Copy") }
            }
            Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                listOf("RAW", "cURL", "FETCH").forEachIndexed { index, label ->
                    if (tab == index) Button(onClick = { tab = index }) { Text(label) }
                    else OutlinedButton(onClick = { tab = index }) { Text(label) }
                }
            }
            Surface(color = GhiInk900.copy(alpha = .8f), shape = MaterialTheme.shapes.small) {
                Text(content, style = MaterialTheme.typography.bodySmall, modifier = Modifier.fillMaxWidth().padding(10.dp))
            }
        }
    }
}

private fun buildPayloads(
    host: String,
    scheme: String,
    method: String,
    path: String,
    userAgent: String,
    extraHeaders: String,
    contentType: String,
    body: String
): List<PayloadVariant> {
    val cleanHost = host.trim()
        .removePrefix("https://")
        .removePrefix("http://")
        .substringBefore("/")
        .trimEnd('.')
    val cleanPath = path.trim().let { if (it.isBlank()) "/" else if (it.startsWith("/")) it else "/$it" }
    val ua = userAgent.trim().ifBlank { CURRENT_CHROME_ANDROID_UA }
    val normalBody = if (method in setOf("POST", "PUT", "PATCH")) body else ""

    val headers = linkedMapOf(
        "Host" to cleanHost,
        "User-Agent" to ua,
        "Accept" to "*/*"
    )
    parseExtraHeaders(extraHeaders).forEach { (name, value) -> headers[name] = value }
    if (normalBody.isNotEmpty()) {
        headers.putIfAbsent("Content-Type", contentType.trim().ifBlank { "application/json" })
        headers["Content-Length"] = normalBody.toByteArray(Charsets.UTF_8).size.toString()
    }

    fun raw(requestTarget: String, requestHeaders: Map<String, String>, requestBody: String = ""): String = buildString {
        append(method).append(' ').append(requestTarget).append(" HTTP/1.1\r\n")
        requestHeaders.forEach { (name, value) -> append(name).append(": ").append(value).append("\r\n") }
        append("\r\n")
        append(requestBody)
    }

    fun curl(url: String): String = buildString {
        append("curl --http1.1 --request ").append(method).append(" ")
        append(shellQuote(url)).append(" ")
        headers.forEach { (name, value) -> append("--header ").append(shellQuote("$name: $value")).append(" ") }
        if (normalBody.isNotEmpty()) append("--data-binary ").append(shellQuote(normalBody))
    }.trim()

    fun fetch(url: String): String = buildString {
        append("fetch(").append(jsQuote(url)).append(", {\n")
        append("  method: ").append(jsQuote(method)).append(",\n")
        append("  headers: {")
        if (headers.isNotEmpty()) append("\n")
        headers.forEach { (name, value) -> append("    ").append(jsQuote(name)).append(": ").append(jsQuote(value)).append(",\n") }
        append("  }")
        if (normalBody.isNotEmpty()) append(",\n  body: ").append(jsQuote(normalBody))
        append("\n});")
    }

    val standardUrl = "$scheme://$cleanHost$cleanPath"
    val keepAliveHeaders = LinkedHashMap(headers).apply { put("Connection", "keep-alive") }
    val wsHeaders = linkedMapOf(
        "Host" to cleanHost,
        "User-Agent" to ua,
        "Accept" to "*/*",
        "Connection" to "Upgrade",
        "Upgrade" to "websocket",
        "Sec-WebSocket-Version" to "13",
        "Sec-WebSocket-Key" to "dGhlIHNhbXBsZSBub25jZQ=="
    )
    val wsRaw = buildString {
        append("GET ").append(cleanPath).append(" HTTP/1.1\r\n")
        wsHeaders.forEach { (name, value) -> append(name).append(": ").append(value).append("\r\n") }
        append("\r\n")
    }

    return listOf(
        PayloadVariant("Standard", raw(cleanPath, headers, normalBody), curl(standardUrl), fetch(standardUrl)),
        PayloadVariant("Absolute-form", raw(standardUrl, headers, normalBody), curl(standardUrl), fetch(standardUrl)),
        PayloadVariant("Keep-Alive", raw(cleanPath, keepAliveHeaders, normalBody), curl(standardUrl), fetch(standardUrl)),
        PayloadVariant("WebSocket Upgrade", wsRaw, "curl --http1.1 -i -N -H 'Connection: Upgrade' -H 'Upgrade: websocket' -H 'Sec-WebSocket-Version: 13' -H 'Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==' ${shellQuote(standardUrl)}", "WebSocket is a handshake template; use a WebSocket client for frames.")
    )
}

private fun parseExtraHeaders(raw: String): List<Pair<String, String>> =
    raw.lineSequence().mapNotNull { line ->
        val index = line.indexOf(':')
        if (index <= 0) return@mapNotNull null
        val name = line.substring(0, index).trim()
        val value = line.substring(index + 1).trim()
        if (name.isBlank() || value.isBlank()) null else name to value
    }.toList()

private fun validateRequest(raw: String): PayloadValidation {
    if (raw.isBlank()) return PayloadValidation(false, "Build a request first.", 0, 0)
    val separator = raw.indexOf("\r\n\r\n")
    if (separator < 0) return PayloadValidation(false, "Missing the required HTTP header/body separator.", raw.toByteArray(Charsets.UTF_8).size, 0)
    val lines = raw.substring(0, separator).split("\r\n")
    val start = lines.firstOrNull().orEmpty().split(' ')
    if (start.size != 3 || start[2] != "HTTP/1.1") return PayloadValidation(false, "The request line is not valid HTTP/1.1 syntax.", raw.toByteArray(Charsets.UTF_8).size, maxOf(0, lines.size - 1))
    if (lines.none { it.startsWith("Host:", true) }) return PayloadValidation(false, "HTTP/1.1 requests need a Host header.", raw.toByteArray(Charsets.UTF_8).size, maxOf(0, lines.size - 1))
    val headerNames = lines.drop(1).mapNotNull { it.substringBefore(':', "").trim().takeIf { n -> n.isNotBlank() } }
    val duplicate = headerNames.groupingBy { it.lowercase() }.eachCount().entries.firstOrNull { it.value > 1 }
    if (duplicate != null) return PayloadValidation(false, "Duplicate header: ${duplicate.key}.", raw.toByteArray(Charsets.UTF_8).size, headerNames.size)
    val body = raw.substring(separator + 4)
    val declared = lines.firstOrNull { it.startsWith("Content-Length:", true) }?.substringAfter(':')?.trim()?.toIntOrNull()
    if (declared != null && declared != body.toByteArray(Charsets.UTF_8).size) return PayloadValidation(false, "Content-Length does not match the UTF-8 body length.", raw.toByteArray(Charsets.UTF_8).size, headerNames.size)
    return PayloadValidation(true, "Request line, Host header, CRLF framing and body length are consistent.", raw.toByteArray(Charsets.UTF_8).size, headerNames.size)
}

private fun shellQuote(value: String): String = "'" + value.replace("'", "'\\''") + "'"
private fun jsQuote(value: String): String = "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\r", "\\r").replace("\n", "\\n") + "\""

@Composable
private fun SchemeButton(label: String, selected: Boolean, onClick: () -> Unit) {
    if (selected) Button(onClick = onClick) { Text(label) }
    else OutlinedButton(onClick = onClick) { Text(label) }
}
